# Generated by Django 4.0.5 on 2022-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=150)),
                ('answer_one', models.TextField(max_length=100)),
                ('answer_two', models.TextField(max_length=100)),
                ('answer_three', models.TextField(max_length=100)),
                ('answer_four', models.TextField(max_length=100)),
            ],
        ),
    ]
