# Generated by Django 4.0.5 on 2022-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_answer_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='skills',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
