# Generated by Django 4.0.5 on 2022-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('special', models.TextField(max_length=250)),
                ('skills', models.TextField(max_length=500)),
            ],
        ),
    ]
